sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: QxgnhhjGrfhIrb4zRVAE9rAIGU878e+WIeYMJ/9BwkGAg5ir9CNOB2cq6HaE/u4qHFIM32Z7oeU1832Ka/qH9VZTu3N7FaWbk/ku4clWMmQP+9x/zzBXtl4+WleACxGCX8Dq6yblFGWfoDyKLunfsLBRZiFut5nepeiZ1LjzNpNA6yB9VsenFpqMfO/jWC7MWN03MXmpr/5cbyF2AoUiSA5V21Yv3BDEkk7fYaQSvmau6e8f34DSEWuVHi48fNwS4J4rKAaSYQCGaxbVmUU12FNHNpt1w0BK3PXW3JJkprqdPxMHNUMH0y4YgPWmPpQnCFEEdsc7Iv256myFpLSielvS9gz6JQ0ksZHUutXdS0p0yRQEYx4hsyL5O/0Fn28jgbXKskbuaKrf/imvhUVUbkDamGvMz7xMhJoOK8iOrf8Iq+gSb7bjHnVT/MVCiNrHnAc8StrHzeBwqeAKnrdvquI1oxW2Uzw8XO1L+oSUR189uanaXJh3AL3GgX4iJ8bosGLpJdn/X8CT0m/5QKCtWICGSgIjQ/bF+cOfRSx6ZpJYQjygVlhlxSKYhqNWzIRc377IcVpRyR9SJ/mB4tSp2pLwgVxVBfHwvijbEqeg4ch79zePS0rsAgIefoF0BCeldmOi2Ts3NRhw4XMn8W7EgdOOHTV5D1J4SZtqEeEkPvo=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Cosmopolis---Complete_3967
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy